### ISSUE TITLE
显示的问题

### ISSUE THREAD

**Issue by NOwin111** [Eroyi/pop-up-search#1]
![QQ截图20231213210448](https://github.com/Eroyi/pop-up-search/assets/64184911/63fa865a-ef75-41de-8bf9-d5712cc447d6)
现在图标上面有这个转发的这个小箭头？？如何不显示？？？

**Comment by dfbb9216** [comment]
改不了的话，老版还有地方下载吗？

**Comment by NOwin111** [comment]
浏览器版本   
百分浏览器版本 5.0.1002.354（正式版本） （64 位） (Portable) (Chromium 102.0.5005.167)

WIN11

**Comment by lianwensheng** [comment]
Me too

**Comment by lianwensheng** [comment]
作者在V2EX给了个解决方法，在 样式设置 > 气泡和小窗 CSS 代码 添加这行样式代码就可以隐藏掉这个角标：

#hcSearcheIcons hcsearche-icon[data-setype="newtab"]::after {display:none}
